replicas: 1
containers:
  image: nginx

  livenessProbe:
    enabled: true
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 3

  readinessProbe:
    enabled: true
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 3
    failureThreshold: 3

  ports:
  - name: http
    containerPort: 80
  resources:
    limits:
      cpu: 250m
      memory: 32Mi
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

service:
  type: ClusterIP
  ports:
  - name: http
    targetPort: 80
    port: 80

ingressNginx:
  ingressClass: nginx
  rewriteTarget: /
  pathUrl: /site
  pathType: Prefix
  number: 80

